### ISSUE TITLE
btn btn-solid-primary not using primary color

### ISSUE THREAD

**Issue by Syiana** [Siumauricio/rippleui#110]
Hello,

I am about to use Rippleui for one of my projects, I created a theme, and when I use "btn-solid-primary" it uses (--blue-4) as the bg color, is this as it should be?

**Comment by Siumauricio** [comment]
Yes this is the expected behavior!

**Comment by tiagoernst** [comment]
So if you want to customise a theme you'd need to redefine every colour & shade ? Is there an easier way to generate the palettes based on the main colours ?
