### ISSUE TITLE
Domain ripple-ui.com has expired

### ISSUE THREAD

**Issue by AlexeyKorkoza** [Siumauricio/rippleui#112]
Hello. I've just tried to visit the site to take a look at the documentation but unfailure.
@Siumauricio Could you please check it?

![Screenshot_556](https://github.com/Siumauricio/rippleui/assets/11200149/868c6f10-1e1c-49d8-a2a5-cabb6b266547)

**Comment by Siumauricio** [comment]
Hey there!, thanks I already fixed!
