### ISSUE TITLE
tailwindcss `darkMode` configuration is not being respected.

### ISSUE THREAD

**Issue by eslym** [Siumauricio/rippleui#117]
**Is your feature request related to a problem? Please describe.**
tailwindcss `darkMode` configuration is not being respected.

```js
module.exports = {
	darkMode: 'class' // this has no effect for ripple ui
}
```

**Describe the solution you'd like**
please add a way to change the theme programmatically

**Comment by Siumauricio** [comment]
That's the tailwindcss configuration you need to pass the right config from ripple ui in to the tailwind config check here 

https://www.ripple-ui.com/docs/get-started/customization#how-to-customize-default-themes

**Comment by eslym** [comment]
i read through the code and realize i can use `data-theme="x"` to achieve what i need, but there is no mention of this in documentation

**Comment by Siumauricio** [comment]
That's correct, that's the way to force a theme
