### ISSUE TITLE
Standalone CLI builds?

### ISSUE THREAD

**Issue by tonyalaribe** [Siumauricio/rippleui#76]
With tailwindcss, the release artifacts include standalone CLI executables which are very convenient as they can be added to CI pipelines without needing CI that supports nodejs in particular. 
https://tailwindcss.com/blog/standalone-cli

Is there a chance to support such executable artifacts in the rippleui releases?

**Comment by Siumauricio** [comment]
Thanks for the suggestion, you can check the executables of the latest version 
https://github.com/Siumauricio/rippleui/releases/tag/v1.9.0
