### ISSUE TITLE
Is this satire?

### ISSUE THREAD

**Issue by kaiserkiwi** [Siumauricio/rippleui#77]
Sorry, I have to ask because I can't find it on the official site. But is this a satirical framework to show how absurd the current Tailwind hype is? Or is this supposed to be a serious framework?

**Comment by Siumauricio** [comment]
I don't know

**Comment by kaiserkiwi** [comment]
I guess this is a no? 😅

**Comment by Siumauricio** [comment]
your comment has no sense, you are just trying to be funny or sarcastic and i dont have time for that, you  need attention at home
