### ISSUE TITLE
Issue with modal

### ISSUE THREAD

**Issue by Fabian9799** [Siumauricio/rippleui#88]
**Describe the bug**
The modal component doesn't seem to work

**To Reproduce**
1. Go to https://www.ripple-ui.com/docs/components/modal
2. copy example
3. add to own code
4. click on button

**Expected behavior**
the modal should open

Is there something specific I need to include to make the modal work or is there some js which is required.
I couldn't find any examples of it working except on the docs page

**Comment by Siumauricio** [comment]
I was checking and I see it there is an error in the order of the `CodeBlock`, you can check it out now it should work, and you don't need JS

**Comment by Fabian9799** [comment]
Works perfectly! Thanks for fixing it that fast
