### ISSUE TITLE
New radix-based color system

### ISSUE THREAD

**Issue by silveltman** [Siumauricio/rippleui#98]
I previously created an issue (https://github.com/Siumauricio/rippleui/issues/97) where I propose better documentation of the current color system. I've spent a lot of time thinking on it and came up with an (in my opinion) improved color system, which better reflects radix's.

I propose the following:
```
	{
		themeName: "light",
		colorScheme: "light",
		colors: {
			base1: "...",
			base2: "...",
			base3: "...",
			base4: "...",
			base5: "...",
			base6: "...",
			base7: "...",
			base8: "...",
			base9: "...",
			base10: "...",
			base11: "...",
			base12: "...",
			primary1: "...",
			primary2: "...",
			primary3: "...",
			// ...
		},
	},
```
By default the base color scale can be set equal to radix's Gray color, since this one is the most neutral. If needed, we could switch it for Slate, Olive etc.

All component should then use base-1 till base-12 by default, which allows us to change all component styling at once by just changes the base colors.

Also, we see the color 'primary' here, which again goed from 1 till 12. We could add the functionality of simply adding a class of 'variant-primary' to anyone of the components, which would simply switch base1 til 12 to primary1 till 12.

This could all be powered by simply using CSS custom properties. A plugin like themer (https://github.com/RyanClementsHax/tailwindcss-themer) can give an idea of how to achieve this. 

To make the configuration for all this even simpler, we could allow something like this (which would be similar to https://github.com/brattonross/windy-radix-palette):
```
const radixColors = require("@radix-ui/colors");

{
	themeName: "light",
	colorScheme: "light",
	colors: {
		base: radixColors.olive
		primary: radixColors.red
	}
}
```

I know I can probably already achieve this rightnow, but I think it would be great if it would have firstclass ripple-ui support.

I would love to know what you guys think of this! :)

**Comment by Siumauricio** [comment]
#97 Related
