### ISSUE TITLE
How can I just keep the dark themes

### ISSUE THREAD

**Issue by Taoaozw** [Siumauricio/rippleui#99]
I only want a dark theme, but my UI has changed due to my macOS system config, and now it shows the light theme. How can I set the dark theme as the only option?

**Comment by Siumauricio** [comment]
Hey @Taoaozw If you want to have only the dark theme you can remove the light theme and you will keep only the dark theme

In your `tailwind.config.js`
```js
/** @type {import('rippleui').Config} */
const config = {
  removeThemes: ["light"]
};

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [],
  theme: {
    extend: {},
  },
  plugins: [
    require("rippleui")({
      ...config,
    }),
  ],
};
```

**Comment by Taoaozw** [comment]
> Hey @Taoaozw If you want to have only the dark theme you can remove the light theme and you will keep only the dark theme
> 
> In your `tailwind.config.js`
> 
> ```js
> /** @type {import('rippleui').Config} */
> const config = {
>   removeThemes: ["light"]
> };
> 
> /** @type {import('tailwindcss').Config} */
> module.exports = {
>   darkMode: "class",
>   content: [],
>   theme: {
>     extend: {},
>   },
>   plugins: [
>     require("rippleui")({
>       ...config,
>     }),
>   ],
> };
> ```
> 
> More information here https://www.ripple-ui.com/docs/get-started/customization#how-to-customize-default-themes

Thank you for your reply, but when i use your suggestion , it don't work well.
 This is my configuration. After turning off the light mode, the webpage remains white instead of switching to dark mode in macOS's light mode. Is there any setting that I might have configured incorrectly?
<img width="650" alt="截屏2023-05-06 22 06 38" src="https://user-images.githubusercontent.com/38341571/236629274-dbb4f598-4c94-4b5f-aef4-e720c87c23d1.png">



<img width="861" alt="截屏2023-05-06 22 06 59" src="https://user-images.githubusercontent.com/38341571/236629279-15af1e48-7adb-4e01-a320-b3d88a9a1630.png">

**Comment by Siumauricio** [comment]
Hey @Taoaozw, Try to add this tag  `data-theme="dark"` at the top root html tag that you have



```diff

+       <section className="pb-20" data-theme="dark"    <- Add this>
           <div className="flex flex-row justify-center px-4 md:gap-24">
          <div className="flex max-w-3xl flex-col gap-4 pt-10 sm:gap-0 sm:pb-24 sm:pt-20  lg:pt-52">
            <div className="flex flex-col gap-4">
              <h1>
                <span className="text-[40px] font-bold leading-none text-primary  sm:text-5xl lg:text-6xl">
                  Ripple Us
                </span>{" "}
                <span className="text-[40px] font-bold leading-none sm:text-5xl lg:text-6xl">
                  Ultimate toolkit for modern interface design.
                </span>
              </h1>
              <p className="pr-10 text-base  text-content2">
                Ripple UI is a collection of components and utilities that are
                used to build modern interfaces. It is built on top of Tailwind
                CSS.
              </p>
            </div>
        </div>
    </div>
</section>
```

**Comment by Taoaozw** [comment]
> ```diff
> data-theme="dark" 
> ```

I wanted to take a moment to thank you for your help. I really appreciate the time and effort you put into assisting me. Your support means a lot to me😊
